### PR TITLE
Props

### PR DESCRIPTION
**Pull request by hosseinghs**
props page translation added

### CODE REVIEW

**Comment by mostafa-nematpour** [comment]
Hi
Have you requested the translation of this page?
https://github.com/vuejs-translations/docs-fa/issues/8

**Comment by hosseinghs** [comment]
No I have not, I've noticed It was being translated but I assumed since my translation is complete I create a pull request

**Comment by mostafa-nematpour** [comment]
Hello @hosseinghs , good time.

Since I didn't hear back for a while, I closed the PR. I've had a private conversation with the requester for this page, and currently, they are not actively translating.
You can go ahead and accept your PR, but please be mindful that translating the new page without coordination might cause confusion.

Thank you.

**Comment by hosseinghs** [comment]
@mostafa-nematpour thank you for your information. glad to be a part of service.

**Pull request merged**
